const PROJECTS_DATA = [
  {
    id: 6,
    name: "Cropifier",
    desc: "Mobile Application that can classify the crop just from the field photo of that crop using Deep Learning. This is a project that I am hugely proud of. This is an application that we created as part of a national hackathon known as Smart India Hackathon 2020. The problem statement was given by the Indian Space Research Organization (ISRO). My team won this competition for our amazing idea & an equally great implementation of the system.",
    image: "/images/Cropifier.png",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
    ],
    date: "Aug, 2020",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:6696722298541490176/?originTrackingId=ZWEtJhXvSfe3ufoC%2FPoa6w%3D%3D",
    type: "MobileApp",
  },
  {
    id: 7,
    name: "LeprosyDetect",
    desc: "Using Mobile Technology to classify the leprosy type of a patient with Deep Learning. Medical applications are really difficult to imagine as they are prone to human errors. But, if the work of doctors and their staff is a little bit easier can help them in huge lengths. So, we continued our Leprosy Project ahead with the creation of a mobile application that can identify the Leprosy type of the patient by taking a photo of the affected part of the skin. This system uses Deep-Learning Models for classification & provides high accuracy for the identification. ",
    image: "/images/LeprosyApp.png",
    tech: [
      { class: "fab fa-js", name: "JS" },
      { class: "fab fa-html", name: "HTML" },
      { class: "fab fa-css", name: "CSS" },
    ],
    date: "--",
    link: "",
    type: "MobileApp",
  },
  {
    id: 8,
    name: "Leprosy Website",
    desc: "The digitizing of manual data is always a tough task as the system should be really simple to understand but equally capable of handling any kind of input and must not face any error. Add a level of difficulty to Medical Data, & this makes it as tough as the words, the kind of medical data that gets stored has to be accurate & error-less. This website was created with the users in mind, & is a collaboration between my college - Shah & Anchor Kutchhi Engineering College with renowned NGO Bombay Leprosy Project, and The International Leprosy Mission: Bangladesh. More details about this project can be found on my GitHub.",
    image: "/images/lep_web1.jpg",
    tech: ["Reactjs", "GSAP", "API"],
    date: "",
    link: "https://www.youtube.com/watch?v=4XM7Ws1j4dE",
    type: "WebSite",
  },
  {
    id: 1,
    name: "Dev Community Clone",
    desc: "Dev Community is Full-stack Blogging Application build with MERN. This project is inspired from dev.to website, I enjoyed and learned a lot while building this. I used React for Front-end User interface, Redux for State Management, Redux thunk for Asynchronous tasks, Express for Backend server, MongoDB Atlas for Database, JSON Web Tokens for Authentications, SHA256 Hashing Algo to hash password and Firbase for storage.",
    image: "/images/1.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
      { class: "/images/redux.svg", name: "Express" },
      { class: "/images/redux.svg", name: "Node" },
      { class: "/images/redux.svg", name: "MongoDB" },
      { class: "/images/firebase.svg", name: "Firebase" },
    ],
    date: "Jun, 2021",
    link: "",
    type: "WebApp",
  },
  {
    id: 2,
    name: "TrackerX",
    desc: "TrackerX is a Full-stack MERN Application for managing finances. I build this App for personal use, I was not able to find an app for managing finances which can fulfill my needs So, I decided to build my own 😋. User can track their expenses and income with various Filter Options. I used React-Bootstrap to build User Interface, Redux to manage state, Express for Backend API server, MongoDB Atlas as Database.",
    image: "/images/2.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
      { class: "/images/redux.svg", name: "Express" },
      { class: "/images/redux.svg", name: "Node" },
      { class: "/images/redux.svg", name: "MongoDB" },
    ],
    date: "--",
    link: "Coming Soon...",
    type: "WebApp",
  },
  {
    id: 3,
    name: "doubts - freelance place",
    desc: "Doubts is freelance platform for teachers or anyone having any skill. This platform provide a direct connection with skilled teachers. User can search for skill which they want to learn and then they have to select a teacher and set-up a video call or chat with them.",
    image: "/images/3.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
      { class: "/images/redux.svg", name: "Express" },
      { class: "/images/redux.svg", name: "Node" },
      { class: "/images/redux.svg", name: "MongoDB" },
    ],
    date: "Coming Soon...",
    link: "Coming Soon...",
    type: "WebApp & Website",
  },
  {
    id: 4,
    name: "My Portfolio 2021",
    desc: "This is the website that I love the most. This is my Portfolio website 2021. This website contains about me and my projects. I used React and GSAP to build this website.",
    image: "/images/4.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "fab fa-react", name: "GSAP" },
    ],
    date: "--",
    link: "--",
    type: "WebSite",
  },
  {
    id: 5,
    name: "Netflix Clone",
    desc: "Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.Netflix clone is a landing page website built using react.",
    image: "/images/5.jpg",
    tech: [
      { class: "fab fa-react", name: "React" },
      { class: "/images/redux.svg", name: "Redux" },
    ],
    date: "Jan, 2021",
    link: "",
    type: "WebApp",
  }
  
];

export default PROJECTS_DATA;
